version: '2'
services:
  dockernodeserver:
    image: dockernodeserver:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_PORT=8080
      - MONGO_HOST=mongodb
    links:
      - mongodb
  mongodb:
    image: sameersbn/mongodb:latest
    ports:
      - "27017:27017"
    restart: always
